body = (
    "<html lang=\"en\">"
    "<head>"
    "  <meta charset=\"UTF-8\">"
    "  <meta name=\"viewport\" content=\"width=device-width,"
    "   initial-scale=1.0\">"
    "  <title>Title</title>"
    "</head>"
    "<body style=\"display: flex; justify-content:"
    "center; width: 100%; flex-direction: column;"
    "align-items: center; position: fixed;"
    "left: 0; top: 0; right: 0; bottom: 0; background-color: #d0cced\">"
    "<h1 style=\"margin: 0 auto 20px\">Welcome to the Book recommender model page"
    "</h1>"
    "	<form class=\"book-sent-form\""
    "    style=\"margin: 0 auto 20px; border: none; display: flex;"
    "	 flex-direction: column; width: 50%; row-gap: 10px\">"
    "    <label for=\"bookNameField\">"
    "    On which book should rely our recommendation?"
    "	 </label>"
    "    <input type=\"text\" id=\"bookNameField\" class=\"bookNameField\""
    "	placeholder=\"Book title\" value=\"16 Lighthouse Road\" />"
    "    <button class=\"searchButton\" type=\"submit\">Search!</button>"
    "  </form>"
    "  <p class=\"result\"></p>"
    "  </br>"
    "  <div>"
    "  Check the docs: <a href=\"/docs\">here</a>"
    "  </div>"
    "  <script>"
    "    async function sendRequest() {\n"
    "      const body = {\n"
    "        input: requestText.value\n"
    "      };\n"
    "      return await fetch(\n"
    "	  \"https://bookrecwebapp.herokuapp.com/api/v1/predict\",\n"
    "	  {\n"
    "        method: \"POST\",\n"
    "        headers: {\n"
    "          Accept: \"application/json\",\n"
    "          \"Content-Type\": \"application/json\"\n"
    "        },\n"
    "        body: JSON.stringify(body),\n"
    "      });\n"
    "    }\n"
    "    const submitRequestButton = document.querySelector(\".searchButton\");\n"
    "    const resultText = document.querySelector(\".result\");\n"
    "    const requestText = document.querySelector(\".bookNameField\")\n"
    "    document.querySelector(\".book-sent-form\").onsubmit = () => false;\n"
    "    document.querySelector(\".book-sent-form\").addEventListener(\n"
    "	\"submit\", \n"
    "	event => event.preventDefault());\n"
    "    submitRequestButton.addEventListener(\"submit\", event => {\n"
    "      event.preventDefault();\n"
    "    });\n"
    "    submitRequestButton.addEventListener(\"click\", () => {\n"
    "      sendRequest().then(response => response.json())\n"
    "        .then(response => {\n"
    "		  console.log(response);\n"
    "          resultText.innerText = '';\n"
    "		  if (response.length == 1) {\n"
    "		    resultText.innerText = response[0]\n"
    "		  }\n"
    "		  else {\n"
    "            for (let i = 1; i < response.length; ++i) {\n"
    "              resultText.innerText += response[i] + '\\n';\n"
    "            }\n"
    "		  }\n"
    "        });\n"
    "    })\n"
    "  </script>"
    "</body>"
    "</html>"
)